version: '3.8'

services:
  database:
    image: eshanrand/voter_database:latest
    container_name: voter_analysis_database
    ports:
      - "27017:27017"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:latest
    container_name: voter_analysis_redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  server:
    image: eshanrand/voter_analysis:latest
    container_name: voter_analysis_server
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # Set the database host to the service name 'database'
      MONGO_URI: mongodb://database:27017/voter_analysis_project
      REDIS_HOST: redis
      REDIS_PORT: 6379
    command: ./gradlew bootrun
    networks:
      - app-network

networks:
  app-network:
